CREATE SEQUENCE INVOICE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE MERCHANT
(
    ID              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    COMPANY_NAME    varchar(100) NOT NULL,
    REGISTRATION_NO varchar(20)  NOT NULL,
    ADDR_LINE_1     varchar(50)  NOT NULL,
    ADDR_LINE_2     varchar(50),
    POSTCODE        varchar(5)   NOT NULL,
    CITY            varchar(20)  NOT NULL,
    STATE           varchar(20)  NOT NULL,
    COUNTRY         varchar(20)  NOT NULL,
    TEL             varchar(20),
    FAX             varchar(20),
    EMAIL           varchar(50),
    BANK_NAME       varchar(50),
    BANK_ACC_NO     varchar(20)
);

CREATE TABLE PRODUCT
(
    ID           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    PRODUCT_NAME varchar(50)    NOT NULL,
    UNIT_PRICE   DECIMAL(10, 2) NOT NULL
);


CREATE TABLE CUSTOMER
(
    ID           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    COMPANY_NAME varchar(100) NOT NULL,
    PIC          varchar(20),
    ADDR_LINE_1  varchar(50)  NOT NULL,
    ADDR_LINE_2  varchar(50),
    POSTCODE     varchar(5)   NOT NULL,
    CITY         varchar(20)  NOT NULL,
    STATE        varchar(20)  NOT NULL,
    COUNTRY      varchar(20)  NOT NULL,
    TEL          varchar(20),
    FAX          varchar(20),
    EMAIL        varchar(50)
);


CREATE TABLE TAX
(
    ID       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    TAX_NAME varchar(20)   NOT NULL,
    RATE     DECIMAL(3, 2) NOT NULL
);

CREATE TABLE DISCOUNT
(
    ID            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    DISCOUNT_NAME varchar(20)   NOT NULL,
    RATE          DECIMAL(3, 2) NOT NULL
);

CREATE TABLE INVOICE
(
    ID             VARCHAR(12) PRIMARY KEY,
    MER_ID         BIGINT         NOT NULL,
    CUS_ID         BIGINT         NOT NULL,
    DIS_ID         BIGINT,
    TAX_ID         BIGINT,
    CREATED_ON     TIMESTAMP      NOT NULL,
    SUBTOTAL       DECIMAL(10, 2) NOT NULL,
    TOTAL_DISCOUNT DECIMAL(10, 2) NOT NULL,
    TOTAL_TAX      DECIMAL(10, 2) NOT NULL,
    TOTAL_PRICE    DECIMAL(10, 2) NOT NULL
);

CREATE TABLE INVOICE_ITEM
(
    ID          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    INV_ID      VARCHAR(12),
    PRO_ID      BIGINT NOT NULL,
    QUANTITY    INTEGER,
    DESCRIPTION VARCHAR(255)
);
